# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- docker

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
    inputs:
      containerRegistry: 'dockerconnection'  # Replace with your Docker Hub service connection name
      repository: 'anwambui/homee'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        v2.0